sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.18.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose build
  - docker-compose run -e MIX_ENV=test www mix do deps.get, compile

script:
  - docker-compose run -e MIX_ENV=test www mix test
  - docker-compose run -e MIX_ENV=test www mix credo
