version: '3'

services:
  www:
    environment:
      - MIX_ENV=dev
    build:
      context: './www'
      dockerfile: 'Dockerfile'
    ports:
      - 4000:4000
    volumes:
      - ./www:/home/elixir/app
